version: '3.9'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                XDE: 1
        image: lara-app
        container_name: lara-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: lara-app
            SERVICE_TAGS: dev
        working_dir: /var/www/html
        ports:
            - ${WEB_HOST_PORT:-8081}:8081
        volumes:
            - .:/var/www/html:cached
            - lara-app-composer:/var/www/html/vendor
            - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./.docker/cron/local-cronjob:/etc/cron.d/cronjob
        networks:
            - app-network
        depends_on:
            - db

    #Database
    db:
        image: postgres
        restart: unless-stopped
        tty: true
        container_name: lara-db
        ports:
            - ${DB_HOST_PORT:-5432}:5432
        environment:
            POSTGRES_DB: ${DB_DATABASE:-lara_db}
            POSTGRES_USER: ${DB_USERNAME:-lara_user}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-lara_pass}
            SERVICE_NAME: lara-db
            SERVICE_TAGS: dev
        volumes:
            - lara-db:/var/lib/postgresql/data
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    lara-db:
        driver: local
    lara-app-composer:
        driver: local
